site_name: appJar
site_url: http://appjar.info
site_favicon: /img/favicon.ico
site_dir: ../../../jarvisteach.github.io/
repo_url: https://github.com/jarvisteach/appJar
google_analytics: ['UA-79206647-1', 'appjar.info']
theme: united
theme_dir: custom_united
copyright: <p>Richard Jarvis, 2016-2017</p>
site_description: Python library for building simple tkinter GUIs
site_author: Richard Jarvis
extra_css: [extra.css]
strict: true
pages:
- Welcome: index.md
- Fillings:
    - Widgets: pythonWidgets.md
    - Images: pythonImages.md
    - Sounds: pythonSound.md
    - Bars: pythonBars.md
    - Pop-ups: pythonDialogs.md
    - Splashscreen: splash.md
    - Special Characters: specialCharacters.md
    - Beta Widgets...: pythonDevWidgets.md
- Configuration:
    - Arranging widgets: pythonWidgetLayout.md
    - Grouping widgets: pythonWidgetGrouping.md
    - Changing widgets: pythonWidgetOptions.md
    - GUI Options: pythonGuiOptions.md
    - GUI Events: pythonEvents.md
    - Drag'n Drop: pythonDnD.md
    - Internationalisation: pythonInternationalisation.md
    - Logging: pythonLogging.md
    - Command Line Arguments: pythonCommandLine.md
- Examples:
    - Raspberry Pi Minecraft: examples/minecraft.md
    - Simple Layout: examples/simple.md
- Help:
    - Guidance: guidance.md
    - Installation: Install.md
    - Python: pythonBasics.md
    - Algorithms: algorithms.md
    - Git: gitGuide.md
    - Packaging: packaging.md
    - Change-Log: whatsNew.md
    - License: License.md
    - Support: Support.md
    - Contributing: contributing.md
    - Acknowledgements: Thanks.md
extra:
    theme_inverse: false
